using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using FakeMG.Framework;
using UnityEditor;
using UnityEditor.Localization;
using UnityEngine.Localization.Tables;

namespace FakeMG.Localization.Editor
{
    public class LocalizationSync : AssetPostprocessor
    {
        private static LocalizationSettingsSO s_cachedSettings;

        static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            if (!s_cachedSettings)
                s_cachedSettings = LocalizationSettingsSO.GetOrCreate();

            var csvPaths = new HashSet<string>();
            foreach (var config in s_cachedSettings.TableConfigs)
            {
                csvPaths.Add(config.CsvPath);
            }

            foreach (string path in importedAssets)
            {
                if (csvPaths.Contains(path))
                {
                    SyncLocalization();
                    return;
                }
            }
        }

        [MenuItem(FakeMGEditorMenus.LOCALIZATION_FORCE_SYNC_CSV)]
        public static void SyncLocalization()
        {
            s_cachedSettings = LocalizationSettingsSO.GetOrCreate();

            if (s_cachedSettings.TableConfigs.Count == 0)
            {
                Echo.Warning("No table configs found in LocalizationSettingsSO.");
                return;
            }

            var allTableEntries = new Dictionary<string, TableSyncResult>();
            int totalKeys = 0;
            int totalRemoved = 0;

            foreach (var config in s_cachedSettings.TableConfigs)
            {
                var result = SyncTable(config);
                if (result == null) continue;

                string className = SanitizeClassName(config.TableCollectionName);
                allTableEntries[className] = result;
                totalKeys += result.Entries.Count;
                totalRemoved += result.RemovedCount;
            }

            GenerateCode(allTableEntries, s_cachedSettings.GeneratedClassPath);

            AssetDatabase.Refresh();
            Echo.Log($"Synced {totalKeys} keys across {allTableEntries.Count} tables, removed {totalRemoved} stale keys.");
        }

        private static TableSyncResult SyncTable(LocalizationTableConfig config)
        {
            string csvPath = config.CsvPath;
            string tableCollectionName = config.TableCollectionName;

            if (!File.Exists(csvPath))
            {
                Echo.Error($"CSV not found at {csvPath}");
                return null;
            }

            string[] lines = File.ReadAllLines(csvPath);
            if (lines.Length < 2) return null;

            List<string> headers = ParseCsvLine(lines[0]);

            StringTableCollection collection = LocalizationEditorSettings.GetStringTableCollection(tableCollectionName);
            if (collection == null)
            {
                Echo.Error($"Localization Table '{tableCollectionName}' not found. Please create it first.");
                return null;
            }

            List<LocEntry> keyData = new();

            for (int i = 1; i < lines.Length; i++)
            {
                if (string.IsNullOrWhiteSpace(lines[i])) continue;

                List<string> columns = ParseCsvLine(lines[i]);
                string key = columns[0].Trim();
                string englishVal = columns[1];

                List<string> args = ExtractArguments(englishVal);
                keyData.Add(new LocEntry { Key = key, English = englishVal, Args = args });

                bool isSmart = args.Count > 0;
                AddOrUpdateTable(collection, headers, key, columns, isSmart);
            }

            HashSet<string> csvKeys = new(keyData.Select(e => e.Key));
            int removedCount = RemoveStaleKeys(collection, csvKeys);

            return new TableSyncResult
            {
                TableCollectionName = tableCollectionName,
                Entries = keyData,
                RemovedCount = removedCount
            };
        }

        private static void GenerateCode(Dictionary<string, TableSyncResult> tableResults, string generatedClassPath)
        {
            StringBuilder sb = new();
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by the LocalizationSync tool.");
            sb.AppendLine("//     Changes to this file will be lost if the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("using UnityEngine.Localization.Settings;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("");
            sb.AppendLine("namespace FakeMG.Localization");
            sb.AppendLine("{");
            sb.AppendLine("\tpublic static class Loc");
            sb.AppendLine("\t{");

            // section: Loc.Get(key) — data-driven lookup across all tables
            GenerateGetMethod(sb, tableResults);

            // section: Per-table nested classes
            foreach (var (className, result) in tableResults)
            {
                GenerateTableClass(sb, className, result);
            }

            sb.AppendLine("\t}");
            sb.AppendLine("}");

            string dir = Path.GetDirectoryName(generatedClassPath);
            if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

            File.WriteAllText(generatedClassPath, sb.ToString());
        }

        private static void GenerateGetMethod(StringBuilder sb, Dictionary<string, TableSyncResult> tableResults)
        {
            sb.AppendLine("\t\tpublic static string Get(string key)");
            sb.AppendLine("\t\t{");
            sb.AppendLine("\t\t\tstring table = ResolveTable(key);");
            sb.AppendLine("\t\t\treturn LocalizationSettings.StringDatabase.GetLocalizedString(table, key);");
            sb.AppendLine("\t\t}");
            sb.AppendLine("");

            sb.AppendLine("\t\tprivate static string ResolveTable(string key)");
            sb.AppendLine("\t\t{");
            sb.AppendLine("\t\t\tswitch (key)");
            sb.AppendLine("\t\t\t{");

            foreach (var (_, result) in tableResults)
            {
                foreach (var entry in result.Entries)
                {
                    sb.AppendLine($"\t\t\t\tcase \"{entry.Key}\":");
                }
                sb.AppendLine($"\t\t\t\t\treturn \"{result.TableCollectionName}\";");
            }

            sb.AppendLine("\t\t\t\tdefault:");
            sb.AppendLine("\t\t\t\t\tthrow new System.ArgumentException($\"Unknown localization key: {key}\");");
            sb.AppendLine("\t\t\t}");
            sb.AppendLine("\t\t}");
            sb.AppendLine("");
        }

        private static void GenerateTableClass(StringBuilder sb, string className, TableSyncResult result)
        {
            string tableName = result.TableCollectionName;
            var entries = result.Entries;

            sb.AppendLine($"\t\tpublic static class {className}");
            sb.AppendLine("\t\t{");

            // Keys sub-class
            sb.AppendLine("\t\t\tpublic static class Keys");
            sb.AppendLine("\t\t\t{");
            foreach (var entry in entries)
            {
                sb.AppendLine($"\t\t\t\tpublic const string {entry.Key} = \"{entry.Key}\";");
            }
            sb.AppendLine("\t\t\t}");
            sb.AppendLine("");

            // Strongly typed methods
            foreach (var entry in entries)
            {
                string methodParams = BuildMethodParams(entry.Args);

                sb.AppendLine($"\t\t\t/// <summary> \"{entry.English}\" </summary>");
                sb.AppendLine($"\t\t\tpublic static string {entry.Key}({methodParams})");
                sb.AppendLine("\t\t\t{");
                if (entry.Args.Count > 0)
                {
                    string dictEntries = string.Join(", ", entry.Args.Select(a => $"{{ \"{a}\", {a} }}"));
                    sb.AppendLine($"\t\t\t\treturn LocalizationSettings.StringDatabase.GetLocalizedString(\"{tableName}\", \"{entry.Key}\", arguments: new Dictionary<string, object>() {{ {dictEntries} }});");
                }
                else
                {
                    sb.AppendLine($"\t\t\t\treturn LocalizationSettings.StringDatabase.GetLocalizedString(\"{tableName}\", \"{entry.Key}\");");
                }
                sb.AppendLine("\t\t\t}");
                sb.AppendLine("");
            }

            sb.AppendLine("\t\t}");
            sb.AppendLine("");
        }

        private static string BuildMethodParams(List<string> args)
        {
            if (args.Count == 0)
                return "";

            return string.Join(", ", args.Select(a => $"object {a}"));
        }

        private static string SanitizeClassName(string tableCollectionName)
        {
            // Remove characters invalid for C# identifiers, keep letters/digits/underscores
            string sanitized = Regex.Replace(tableCollectionName, @"[^a-zA-Z0-9_]", "");

            if (sanitized.Length == 0 || char.IsDigit(sanitized[0]))
                sanitized = "_" + sanitized;

            return sanitized;
        }

        // --- Helpers ---

        private static int RemoveStaleKeys(StringTableCollection collection, HashSet<string> csvKeys)
        {
            var sharedEntries = collection.SharedData.Entries;
            var staleEntries = sharedEntries
                .Where(e => !csvKeys.Contains(e.Key))
                .ToList();

            foreach (var staleEntry in staleEntries)
            {
                collection.SharedData.RemoveKey(staleEntry.Id);
            }

            if (staleEntries.Count > 0)
            {
                EditorUtility.SetDirty(collection.SharedData);

                foreach (var table in collection.StringTables)
                {
                    EditorUtility.SetDirty(table);
                }
            }

            return staleEntries.Count;
        }

        private static void AddOrUpdateTable(StringTableCollection collection, List<string> headers, string key, List<string> columns, bool isSmart)
        {
            for (int colIndex = 1; colIndex < headers.Count && colIndex < columns.Count; colIndex++)
            {
                string localeCode = headers[colIndex].Trim();
                StringTable table = FindTableByLocaleCode(collection, localeCode);
                if (table == null) continue;

                StringTableEntry entry = table.GetEntry(key) ?? table.AddEntry(key, columns[colIndex]);
                entry.Value = columns[colIndex];
                entry.IsSmart = isSmart;
                EditorUtility.SetDirty(table);
            }
        }
        private static StringTable FindTableByLocaleCode(StringTableCollection collection, string localeCode)
        {
            // Matches CSV header against: EnglishName ("English"), NativeName ("Tiếng Việt"),
            // CultureInfo.Name ("en"), TwoLetterISO ("vi"), or LocaleIdentifier.Code as fallback.
            return collection.StringTables
                .FirstOrDefault(t =>
                {
                    var cultureInfo = t.LocaleIdentifier.CultureInfo;
                    if (cultureInfo != null)
                    {
                        if (string.Equals(cultureInfo.EnglishName, localeCode, System.StringComparison.OrdinalIgnoreCase)
                            || string.Equals(cultureInfo.NativeName, localeCode, System.StringComparison.OrdinalIgnoreCase)
                            || string.Equals(cultureInfo.Name, localeCode, System.StringComparison.OrdinalIgnoreCase)
                            || string.Equals(cultureInfo.TwoLetterISOLanguageName, localeCode, System.StringComparison.OrdinalIgnoreCase))
                        {
                            return true;
                        }
                    }

                    return string.Equals(t.LocaleIdentifier.Code, localeCode, System.StringComparison.OrdinalIgnoreCase);
                });
        }

        private static List<string> ParseCsvLine(string line)
        {
            // Simple comma split, robust CSV parser recommended for production (e.g. handling commas in quotes)
            return new List<string>(line.Split(','));
        }

        private static List<string> ExtractArguments(string text)
        {
            var args = new List<string>();
            // Matches Smart String placeholders with optional formatting, e.g. {name} or {gender:choose(...):...}
            var matches = Regex.Matches(text, @"(?<!\{)\{([a-zA-Z_][a-zA-Z0-9_]*)(?=[,:}])");
            foreach (Match m in matches)
            {
                string arg = m.Groups[1].Value;
                if (!args.Contains(arg)) args.Add(arg);
            }
            return args;
        }

        private struct LocEntry
        {
            public string Key;
            public string English;
            public List<string> Args;
        }

        private class TableSyncResult
        {
            public string TableCollectionName;
            public List<LocEntry> Entries;
            public int RemovedCount;
        }
    }
}