using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using FakeMG.Framework;
using UnityEditor;
using UnityEditor.Localization;
using UnityEngine;
using UnityEngine.Localization.Tables;

namespace FakeMG.Localization
{
    public class LocalizationSync : AssetPostprocessor
    {
        private const string CSV_PATH = "Assets/Localization/Localization.csv"; // Path to your CSV
        private const string GENERATED_CLASS_PATH = "Assets/Scripts/Generated/Loc.cs"; // Path to generate code
        private const string TABLE_COLLECTION_NAME = "Test"; // Name of your Unity Localization Table

        // Trigger when CSV is modified
        static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            foreach (string str in importedAssets)
            {
                if (str.Equals(CSV_PATH))
                {
                    SyncLocalization();
                    return;
                }
            }
        }

        [MenuItem(FakeMGEditorMenus.LOCALIZATION_FORCE_SYNC_CSV)]
        public static void SyncLocalization()
        {
            if (!File.Exists(CSV_PATH)) { Debug.LogError("CSV not found at " + CSV_PATH); return; }

            string[] lines = File.ReadAllLines(CSV_PATH);
            if (lines.Length < 2) return;

            // 1. Parse CSV Headers (Languages)
            List<string> headers = ParseCsvLine(lines[0]);
            // Assuming: Index 0 = Key, Index 1 = English (Default), Index 2+ = Locales

            // 2. Load Unity Localization Table
            StringTableCollection collection = LocalizationEditorSettings.GetStringTableCollection(TABLE_COLLECTION_NAME);
            if (collection == null)
            {
                Debug.LogError($"Localization Table '{TABLE_COLLECTION_NAME}' not found. Please create it first.");
                return;
            }

            // 3.1. Parse CSV and Sync with Unity Tables
            List<LocEntry> keyData = new();

            for (int i = 1; i < lines.Length; i++)
            {
                if (string.IsNullOrWhiteSpace(lines[i])) continue;

                List<string> columns = ParseCsvLine(lines[i]);
                string key = columns[0].Trim();
                string englishVal = columns[1];

                // Extract Arguments {name} using Regex
                List<string> args = ExtractArguments(englishVal);
                keyData.Add(new LocEntry { Key = key, English = englishVal, Args = args });

                // Update Unity Table
                bool isSmart = args.Count > 0;
                AddOrUpdateTable(collection, headers, key, columns, isSmart);
            }

            // 3.2. Remove stale keys not present in CSV
            HashSet<string> csvKeys = new(keyData.Select(e => e.Key));
            int removedCount = RemoveStaleKeys(collection, csvKeys);

            // 5. Generate C# Code
            GenerateCode(keyData);

            AssetDatabase.Refresh();
            Debug.Log($"<b>[Localization]</b> Synced {keyData.Count} keys, removed {removedCount} stale keys from CSV.");
        }

        private static void GenerateCode(List<LocEntry> entries)
        {
            StringBuilder sb = new();
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by the LocalizationSync tool.");
            sb.AppendLine("//     Changes to this file will be lost if the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("using UnityEngine.Localization;");
            sb.AppendLine("using UnityEngine.Localization.Settings;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("");
            sb.AppendLine("namespace FakeMG.Localization");
            sb.AppendLine("{");
            sb.AppendLine("\tpublic static class Loc");
            sb.AppendLine("\t{");

            // section: Const Keys (For ScriptableObjects/Inspectors)
            sb.AppendLine("\t\tpublic static class Keys");
            sb.AppendLine("\t\t{");
            foreach (var entry in entries)
            {
                sb.AppendLine($"\t\t\tpublic const string {entry.Key} = \"{entry.Key}\";");
            }
            sb.AppendLine("\t\t}");
            sb.AppendLine("");

            // section: Strongly Typed Methods
            sb.AppendLine("\t\t// Runtime Methods");
            foreach (var entry in entries)
            {
                string methodParams = "";

                if (entry.Args.Count > 0)
                {
                    // Create "object argName, object argName2"
                    List<string> p = new();
                    foreach (var arg in entry.Args)
                    {
                        p.Add($"object {arg}");
                    }
                    methodParams = string.Join(", ", p);
                }

                sb.AppendLine($"\t\t/// <summary> \"{entry.English}\" </summary>");
                sb.AppendLine($"\t\tpublic static string {entry.Key}({methodParams})");
                sb.AppendLine("\t\t{");
                if (entry.Args.Count > 0)
                {
                    string dictEntries = string.Join(", ", entry.Args.Select(a => $"{{ \"{a}\", {a} }}"));
                    sb.AppendLine($"\t\t\treturn LocalizationSettings.StringDatabase.GetLocalizedString(\"{TABLE_COLLECTION_NAME}\", \"{entry.Key}\", arguments: new Dictionary<string, object>() {{ {dictEntries} }});");
                }
                else
                {
                    sb.AppendLine($"\t\t\treturn LocalizationSettings.StringDatabase.GetLocalizedString(\"{TABLE_COLLECTION_NAME}\", \"{entry.Key}\");");
                }
                sb.AppendLine("\t\t}");
                sb.AppendLine("");
            }

            sb.AppendLine("\t}");
            sb.AppendLine("}");

            // Create directory if missing
            string dir = Path.GetDirectoryName(GENERATED_CLASS_PATH);
            if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

            File.WriteAllText(GENERATED_CLASS_PATH, sb.ToString());
        }

        // --- Helpers ---

        private static int RemoveStaleKeys(StringTableCollection collection, HashSet<string> csvKeys)
        {
            var sharedEntries = collection.SharedData.Entries;
            var staleEntries = sharedEntries
                .Where(e => !csvKeys.Contains(e.Key))
                .ToList();

            foreach (var staleEntry in staleEntries)
            {
                collection.SharedData.RemoveKey(staleEntry.Id);
            }

            if (staleEntries.Count > 0)
            {
                EditorUtility.SetDirty(collection.SharedData);

                foreach (var table in collection.StringTables)
                {
                    EditorUtility.SetDirty(table);
                }
            }

            return staleEntries.Count;
        }

        private static void AddOrUpdateTable(StringTableCollection collection, List<string> headers, string key, List<string> columns, bool isSmart)
        {
            for (int colIndex = 1; colIndex < headers.Count && colIndex < columns.Count; colIndex++)
            {
                string localeCode = headers[colIndex].Trim();
                StringTable table = FindTableByLocaleCode(collection, localeCode);
                if (table == null) continue;

                StringTableEntry entry = table.GetEntry(key) ?? table.AddEntry(key, columns[colIndex]);
                entry.Value = columns[colIndex];
                entry.IsSmart = isSmart;
                EditorUtility.SetDirty(table);
            }
        }
        private static StringTable FindTableByLocaleCode(StringTableCollection collection, string localeCode)
        {
            // Matches CSV header against: EnglishName ("English"), NativeName ("Tiếng Việt"),
            // CultureInfo.Name ("en"), TwoLetterISO ("vi"), or LocaleIdentifier.Code as fallback.
            return collection.StringTables
                .FirstOrDefault(t =>
                {
                    var cultureInfo = t.LocaleIdentifier.CultureInfo;
                    if (cultureInfo != null)
                    {
                        if (string.Equals(cultureInfo.EnglishName, localeCode, System.StringComparison.OrdinalIgnoreCase)
                            || string.Equals(cultureInfo.NativeName, localeCode, System.StringComparison.OrdinalIgnoreCase)
                            || string.Equals(cultureInfo.Name, localeCode, System.StringComparison.OrdinalIgnoreCase)
                            || string.Equals(cultureInfo.TwoLetterISOLanguageName, localeCode, System.StringComparison.OrdinalIgnoreCase))
                        {
                            return true;
                        }
                    }

                    return string.Equals(t.LocaleIdentifier.Code, localeCode, System.StringComparison.OrdinalIgnoreCase);
                });
        }

        private static List<string> ParseCsvLine(string line)
        {
            // Simple comma split, robust CSV parser recommended for production (e.g. handling commas in quotes)
            return new List<string>(line.Split(','));
        }

        private static List<string> ExtractArguments(string text)
        {
            var args = new List<string>();
            // Matches Smart String placeholders with optional formatting, e.g. {name} or {gender:choose(...):...}
            var matches = Regex.Matches(text, @"(?<!\{)\{([a-zA-Z_][a-zA-Z0-9_]*)(?=[,:}])");
            foreach (Match m in matches)
            {
                string arg = m.Groups[1].Value;
                if (!args.Contains(arg)) args.Add(arg);
            }
            return args;
        }

        private struct LocEntry
        {
            public string Key;
            public string English;
            public List<string> Args;
        }
    }
}